### ISSUE TITLE
Missing value in the pre-trained model

### ISSUE THREAD

**Issue by SifanW** [Yevkuzn/semodepth#2]
After downloading the "model" and modify config.py file, an error occurred.

tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "block1/batchnorm_offset1" not found in checkpoint files /media/data/sifan/Depth_estimation/semodepth/best_model/depth-chkpt.index

**Comment by Yevkuzn** [comment]
Oh, I forgot to mention that there should be no extension (e.g., depth-chkpt instead of depth-chkpt.index).
Hope, this solves your problem. I also updated the parameter description in the config file.
