### ISSUE TITLE
Question about hyperparameters

### ISSUE THREAD

**Issue by pjckoch** [Yevkuzn/semodepth#4]
Hi, 

first of all thanks for sharing your work. I have a question about your paper. You stated the following in your Implementation Details:

> To achieve a convergent optimization, we slowly fade-in the supervised loss with the number of iterations using <img src="http://www.sciweavers.org/tex2img.php?eq=%20%5Clambda_t%20%3D%20%20%5Cbeta%20%2A%20%20e%5E%7B-10%2Ft%7D%20&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt=" \lambda_t =  \beta *  e^{-10/t} " width="124" height="22" />

Which value did you end up using for \beta ? And does **t** refer to the epoch or iteration? Sorry in case I overlooked it in the paper, but I think you did not provide details on those.

Thanks in advance!

**Comment by Yevkuzn** [comment]
Hi,
t definitely refers to the iteration.
As for beta, unfortunately I don't remember the exact value used. But I can assume it was in the [0.1; 10] range, which should be reasonable for the weight of the supervised term.  Most likely 1.0, or 0.5.
I will check the project files for the value of beta, but no guarantee I can find it after several years.

Also, it is off topic, but I recommend using a multi-scale image reconstruction loss term for enhancing supervised depth estimation. 
It worked with a single-scale variant, and was easier to implement, but the multi-scale variant should be more robust.

Hope this answer helps

**Comment by pjckoch** [comment]
Hi,

thanks for the prompt response.

Ok thanks for the clarification. I know that the quote from above strongly implies that **t** refers to iterations, but I was a bit confused since that would mean that exp(-10/t) already equals 0.99 after 1000 iterations. I would have guessed that the fading in would be a bit more gradual. Do you happen to remember whether you tested out different exponents, e.g. exp(-100/t), exp(-1000/t) ? If not, don't worry, you've helped me enough already.

And thank you very much for the advice. I also noticed that recent works follow a multi-scale approach and I plan to do it similarly.

Thanks again and have a great week!
