### ISSUE TITLE
Mat to image

### ISSUE THREAD

**Issue by Machine-NO-Learning** [Yevkuzn/semodepth#5]
Hi, i met the problem about changing the mat to image, after predication by using produce_predictions.py, then i find my image mat shape is (1, 864, 1232, 1) which can't convert to image, i am not sure whether my operation is correct or not, thanks a lot

**Comment by Yevkuzn** [comment]
Hi, sorry for replying late. Could you please tell me your input image resolution?

**Comment by Machine-NO-Learning** [comment]
So sorry too late for replying it, I have successfully done it, thanks and cheers
